name: go-qrcode

on:
  push:

jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      tags: waterlemons2k/go-qrcode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
